### ISSUE TITLE
Invalid CKAN resource URL generated

### ISSUE THREAD

**Issue by jindrichmynarz** [OpenDataNode/UVPlugin-rdfToCKAN#1]
Not sure whether this is an issue of this DPU, or the CKAN glue code (e.g., `http://localhost:9080/internalcatalog/api/action/internal_api`), or of ODN. Let me know if I should move the issue elsewhere.

The DPU creates an invalid CKAN resource URL. First, ODN 1.0.1 runs the Virtuoso SPARQL endpoint on the port 8890 (i.e. `http://localhost:8890/sparql`), whereas the URLs generated by this DPU expect it to be running on the default HTTP port (i.e. `http://localhost/sparql`).

**Comment by skrchnavy** [comment]
Second issue removed and new issue created, see #3

**Comment by skrchnavy** [comment]
Based on implementation of OpenDataNode/UVPlugin-filesToCKAN#2 and OpenDataNode/UVPlugin-filesToCKAN@e90606e937f0e27ac35f86c8b499fd5a20f450f6
it shall be supported configuration of http headers sent to CKAN
for of configuration:
`org.opendatanode.CKAN.http.header.[key]  = [value]`
where:
     [key] is header name 
     [value] is header value
